### ISSUE TITLE
apicup registry-upload command gave error during image upload

### ISSUE THREAD

**Issue by vishalk663** [mr-yadav235/apiconnect-openshift#1]
apicup registry-upload command gave an error 
```
Error: registry URL is invalid: parse "xx.xx.xx.xx:5000": first path segment in URL cannot contain colon
```
 when using IP address of docker-registry svc.

**Comment by mr-yadav235** [comment]
Kindly use Openshift to create svc for docker registry, and create Route for the same service, and use the route URL.

**Comment by mr-yadav235** [comment]
No updates. Marking it as problem solved.
